Add Domainname.shop
duffn/dumb-password-rules pull request #513
Opened 2023-05-08 07:46 UTC by mdavidsen

domainname.shop operates under several domains, domene.shop (Norway), domän.shop (Sweeden), domæne.shop (Denmark). 
The following characters are allowed: `A-Z, a-z, 0-9 and + - * / ! ? . , : ; = # @ $ % & ( ) < >`, password lenght 10-79 chars

2023-05-08 16:42 UTC, duffn requested changes
Thanks, just a few notes!

2023-05-08 16:42 UTC, duffn commented on src/_data/sites/domainname.shop.yaml
> +    The following characters are allowed: A-Z, a-z, 0-9 and + - * / ! ? . , : ; = # @ $ % & ( ) < >, password lenght 10-79 chars
Length is misspelled here.

2023-05-08 16:42 UTC, duffn commented on src/_data/sites/domainname.shop.yaml
> +url: https://domainname.shop
Nit: can you add a new line at the end of the file please.

2023-05-11 22:20 UTC, mdavidsen commented
Commets fixed and pushed :)

2023-05-12 01:53 UTC, duffn approved these changes

2023-05-12 01:53 UTC, merged

2023-05-12 01:53 UTC, duffn commented
Thank you for the contribution!